services:
  dns:
    build:
      context: ./dns
      dockerfile: Dockerfile
    container_name: dns 
    ports:
      - "53:53/udp"

  web01:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: web01 


  web02:
    build:
      context: ./web02
      dockerfile: Dockerfile
    container_name: web02 


  proxy:
    build: 
      context: ./proxy
      dockerfile: Dockerfile
    container_name: proxy
    ports:
      - "80:80/tcp"
